---

- name: Adding group
  group: >
    name={{ sftp_users_group }}
    state=present
  when: sftp_users_group is defined
  tags:
    - networking
    - sftp
    - config

- name: Registering nologin shell
  lineinfile: >
    state=present
    dest=/etc/shells
    line="/usr/sbin/nologin"
    regexp="^/usr/sbin/nologin"
    insertafter=EOF
  tags:
    - networking
    - sftp
    - config

- name: Configuring sshd subsystem
  lineinfile: >
    state=present
    dest=/etc/ssh/sshd_config
    validate="/usr/sbin/sshd -T -f %s"
    line="Subsystem sftp internal-sftp"
    regexp="^Subsystem sftp"
  notify: restart ssh
  tags:
    - networking
    - sftp
    - config

- name: Clearing sshd config
  command: >
    sed -in '/{{ sftp_placeholder_start }}/,/{{ sftp_placeholder_end }}/d' /etc/ssh/sshd_config
  notify: restart ssh
  tags:
    - networking
    - sftp
    - config

- name: Adding sshd config placeholder
  lineinfile: >
    state=present
    dest=/etc/ssh/sshd_config
    validate="/usr/sbin/sshd -T -f %s"
    line="{{ '\n' ~ sftp_placeholder_start ~ '\n' ~ sftp_placeholder_end }}"
  tags:
    - networking
    - sftp
    - config
